Question_Answer/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('account.urls', 'account'), namespace='account')),
]

account/urls.py
from django.urls import path,include
from .views import (IndexView,LoginView,SignupView,LogoutView,UserProfileView,GetAllUrlsView)

urlpatterns = [

    path('',LoginView.as_view(),name="login_view"),
    path('signup/', SignupView.as_view(), name="sign_up_view"),
    path('index/', IndexView, name="index_view"),
    path('logout/', LogoutView.as_view(), name="logout_view"),
    path('user/profile/', UserProfileView, name="user_profile_view"),
    path('get/urls/', GetAllUrlsView.as_view(), name="get_all_urls_view")

]

account/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.decorators import login_required
from bs4 import BeautifulSoup
import requests
import time
from random import randint
import random
from time import sleep

# Create your views here.

class LoginView(View):

    def get(self,request):
        template_name = "login.html"
        context = {}
        return render(request, template_name, context)

    def post(self,request):
        if request.method == "POST":
            # check user and password is authenticated or not
            user = authenticate(username=request.POST["username"],password=request.POST["pass"])
            if user is not None:
                # go to login
                login(request,user)
                return redirect('index/')
            else:
                return render(request,template_name="login.html",context={
                    "error":"Invalid Login Credentials"
                })
        else:
            return render(request,template_name="login.html")

class SignupView(View):

    def get(self,request):
        template_name = "registration.html"
        context = {}
        return render(request, template_name, context)

    def post(self,request):
        template_name = "registration.html"
        print("Request Data :",request.POST)
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
        print("User Name :",username)
        print("User email :",email)
        print("User password :",password)
        print("User confirm_password :",confirm_password)
        print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")

        if request.method == "POST":
            # to create a user
            if password == confirm_password:
                try:
                    user = User.objects.get(username=username)
                    context = {
                        "error":"User name Is Already Taken"
                    }
                    return render(request,template_name,context)
                except User.DoesNotExist:
                    user = User.objects.create_user(username=username,email=email,password=password)
                    return redirect('/')
            else:
                context = {
                    "error":"Passwords does not match !"
                }
                return render(request,template_name,context)
        else:
            return render(request,template_name)

@login_required(login_url='/')
def IndexView(request):
    template_name = "index.html"
    print("request.user :",request.user)
    quertset = User.objects.get(username=request.user)
    print("User Id :",quertset.email)
    context = {
        "usename":request.user
    }
    return render(request, template_name, context)


# class IndexView(View):
#
#     @login_required(login_url='/')
#     def get(self,request):
#         template_name = "index.html"
#         print("request.user :",request.user)
#         quertset = User.objects.get(username=request.user)
#         print("User Id :",quertset.email)
#         context = {
#             "usename":request.user
#         }
#         return render(request, template_name, context)
#
#     def post(self,request):
#         self.get(request)

class LogoutView(View):

    def get(self,request):
        logout(request)
        return redirect('/')

    def post(self,request):
        self.get(request)

@login_required(login_url='/')
def UserProfileView(request):
    template_name = "profile.html"
    print("request.user : ",request.user)
    queryset = User.objects.get(username=request.user)
    context = {
        "username": queryset.username,
        "email": queryset.email,
        "password": queryset.password
    }
    return render(request, template_name, context)

def getRequest(websiteUrl):
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
            }
        # hit the website url
        session = requests.Session()
        response = session.get(websiteUrl, headers=headers, verify=False)

        if response.status_code == 200:
            sleep(randint(1, 1))
            beautifyData = BeautifulSoup(response.content, 'html.parser')
            return beautifyData
        else:
            return None
    except Exception as e:
        print("Error IN : Custom Error in getRequest",e)


class GetAllUrlsView(View):

    def get(self,request):
        self.get(request)

    def post(self,request):
        template_name = "index.html"
        search_term = request.POST["search_term"]
        print("$$$$$$$$$$$$$$$$$$$$$$$$")
        print(search_term)
        print("$$$$$$$$$$$$$$$$$$$$$$$$")
        if search_term:
            base_url = 'https://www.google.com/search?q={0}'.format(search_term)

        soup = getRequest(base_url)

        print("Soup Html :",soup)

        wrong_search_keyword = 'Your search - ' + search_term + ' - did not match any documents.'

        if soup == None:
            return HttpResponse("Something Went Wrong!!! Please try again")
        else:
            soup_page_for_wrong_input = soup.findAll('div', {'class': 'card-section'})

            if soup_page_for_wrong_input :
                for wrong in soup_page_for_wrong_input:
                    if wrong.select('p'):
                        if wrong.select('p')[0].get_text() == wrong_search_keyword:
                            print("did not match any documents.!!!!!!")
                            context = {
                                "status":True,
                                "result_status":False,
                                "result": "Your search - {} - did not match any documents.".format(search_term)
                            }
                            return render(request,template_name,context)

            list_of_urls_and_description = []
            rating_count = 5
            all_matching_urls = soup.findAll('h3',{'class':'LC20lb DKV0Md'})
            print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
            for url in all_matching_urls:
                # print(url.find_previous('a').get("href"))
                # print(url.find_next('div',{'class':'s'}).find_next('span',{'class':'st'}).get_text())
                # list_of_url_description.append(url.find_next('div',{'class':'s'}).find_next('span',{'class':'st'}).get_text())
                # list_of_urls.append(url.find_previous('a').get("href"))
                answer_dict = {
                    "link":url.find_previous('a').get("href"),
                    # "description":url.find_next('div',{'class':'s'}).find_next('span',{'class':'st'}).get_text(),
                    "rating":range(rating_count)
                }
                list_of_urls_and_description.append(answer_dict)
                rating_count -= 1

            print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
            print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
            print(list_of_urls_and_description)
            print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
            context = {
                "status": True,
                "result_status": True,
                "usename": request.user,
                "result":list_of_urls_and_description,
                "search_term":search_term
            }
            return render(request, template_name, context)

templates/index.html
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>QuestionAndAnswerBank</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Custom fonts for this template -->
  <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<style>
.checked {
  color: orange;
}
</style>
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'account:index_view' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Question Bank</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:index_view' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <form class="form-inline">
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>
          </form>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% if usename %} {{ usename }} {% endif %}</span>
<!--                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'account:user_profile_view' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
        <form class="user" method="post" action="{% url 'account:get_all_urls_view' %}">
            {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="search_term" name="search_term" placeholder="Search Google or type a URL">
                  </div>
                  <div class="col-sm-2 mb-3 mb-sm-0">
                     <button class="btn btn-primary btn-user btn-block">
                       Google Search
                     </button>
                  </div>

                <hr>

                </div>
              </form>
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Matching Answer Listing</h6><br>
              {% if search_term %}
              <h6 class="m-0 font-weight-bold text-primary"> Your Question: <font color="orange"> {{ search_term }} </font></h6>
              {% endif %}
            </div>

            <div class="card-body">
              <div class="table-responsive">
                {% if result_status == False %}
                  <h6 style="color:red;">  {{ result }} </h6>
                  {% endif %}
                {% if result_status == True %}
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Answer URl</th>
                      <th>Rating</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                     <th>Answer URl</th>
                      <th>Rating</th>
                    </tr>
                  </tfoot>
                  <tbody>
                  {% for url in result %}
                  <tr>
                    <td>
                      <a href=" {{ url.link }}"> {{ url.link }}</a>
                      <h6>{{ url.description }}</h6>
                    </td>
                    <td>
                      {% if url.rating %}
                        {% for rat in url.rating %}
                          <span class="fa fa-star checked"></span>
                        {% endfor %}
                      {% else %}
                        <span class="fa fa-star checked"></span>
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
                {% endif %}
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Question and Answer Bank Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'account:logout_view' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

</body>

</html>

templates/login.html

{% load static %}

<html lang="en">
<head>
	<title>QuestionAndAnswer | SignIn </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login_theme/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login_theme/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">

				<div class="login100-form-title" style="background-image: url(static/login_theme/images/bg-01.jpg);">
					<h4 style="color:white;"><u><b>Question And Answer Bank</b></u></h4>
					<span class="login100-form-title-1">
						<h5  style="padding-top:5px;">Sign In</h5>
					</span>

				</div>

				<form method="post" class="login100-form validate-form">
					{% csrf_token %}
					{% if error %}<h6 style="color:red;"> {{ error }} 	{% endif %}</h6>
					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Enter username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="pass" placeholder="Enter password">
						<span class="focus-input100"></span>
					</div>

					<div class="flex-sb-m w-full p-b-30">
<!--						<div class="contact100-form-checkbox">-->
<!--							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">-->
<!--							<label class="label-checkbox100" for="ckb1">-->
<!--								Remember me-->
<!--							</label>-->
<!--						</div>-->

<!--						<div>-->
<!--							<a href="#" class="txt1">-->
<!--								Forgot Password?-->
<!--							</a>-->

<!--						</div>-->


					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login

						</button>
							<a href="{% url 'account:sign_up_view' %}" style="padding-left:120px;">
								<u>Create Account</u>
							</a>
					</div>




				</form>

			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="{% static 'login_theme/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login_theme/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login_theme/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login_theme/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login_theme/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login_theme/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login_theme/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login_theme/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login_theme/js/main.js' %}"></script>

</body>
</html>

templates/profile.html
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>QuestionAndAnswerBank</title>

  <!-- Custom fonts for this template -->
  <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Question Bank</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:index_view' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <form class="form-inline">
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>
          </form>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% if username %} {{ username }} {% endif %}</span>
<!--                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'account:user_profile_view' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->
<img src="{% static 'images/profile_logo2.webp' %}" style="margin-left:350px;" width="25%" height="40%"><br><br>
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <form class="user">
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-3">
                    <input readonly type="text" class="form-control form-control-user" id="Username" placeholder="" value="Username : {{ username }}">
                  </div>
                    <div class="col-sm-6 mb-3 mb-sm-3">
                    <input readonly type="text" class="form-control form-control-user" id="Email" placeholder="" value="Email : {{ email }}">
                  </div>

<!--                  <div class="col-sm-6 mb-3 mb-sm-3">-->
<!--                    <input type="text" class="form-control form-control-user" id="Password" placeholder="" value="{{ password }}">-->
<!--                  </div>-->

<!--                  <div class="col-sm-2 mb-3 mb-sm-3">-->
<!--                     <a href="login.html" class="btn btn-primary btn-user btn-block">-->
<!--                       Update Profile-->
<!--                    </a>-->
<!--                  </div>-->

                <hr>

                </div>
          </form>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'account:logout_view' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'dashboard/js/demo/datatables-demo.js' %}"></script>

</body>

</html>